export { default as imgLogo } from './img_logo.svg';
export { default as imgEmptyProfile } from './img_empty_profile.svg';
export { default as imgEmptyJoinProfile } from './img_empty_join.svg';
export { ReactComponent as ImgTeamAdd } from './img_team_add.svg';
export { default as imgComputer } from './img_computer.svg';
export { ReactComponent as ImgBackgroundEllipse } from './img_background_ellipse.svg';
export { ReactComponent as ImgQuestionFrame } from './img_question_frame.svg';
export { ReactComponent as ImgNewLink } from './img_new_link.svg';
export { ReactComponent as ImgCreatedLink } from './img_created_link.svg';
