export { default as icPlus } from './ic_plus.svg';
export { default as icCamera } from './ic_camera.svg';
export { default as icKakao } from './ic_kakao.svg';
export { default as icEmail } from './ic_email.svg';
export { ReactComponent as IcSearch } from './ic_search.svg';
export { ReactComponent as IcBack } from './ic_back.svg';
export { ReactComponent as IcDelete } from './ic_delete.svg';
export { ReactComponent as IcMemberAdd } from './ic_member_add.svg';
export { ReactComponent as IcPencil } from './ic_pencil.svg';
